[config]
model = "azure/gpt-4"
model_turbo = "azure/gpt-4"
fallback_models = ["azure/gpt-4"]
custom_model_max_tokens = 128000

[openai]
api_type = "azure"
api_version = "2025-04-01"

[pr_reviewer]
model = "azure/gpt-4"
model_turbo = "azure/gpt-4"

[pr_description]
model = "azure/gpt-4"

[pr_code_suggestions]
model = "azure/gpt-4"
